const vscode = require('vscode');
const assert = require('node:assert/strict');
exports.run = async () => {
  const manifest = require('../package.json');
  const extension = vscode.extensions.getExtension(`${manifest.publisher}.${manifest.name}`);
  assert(extension, 'Extension discovered');
  const api = await extension.activate();
  const doc = await vscode.workspace.openTextDocument({ language: 'yaml', content: 'proxies:\n  - name: 🇭🇰 Test\n    type: socks5\nproxy-groups:\n  - name: AI\n    type: select\n    proxies:\n      - DIRECT\n      - 🇭🇰 Test\n' });
  await vscode.window.showTextDocument(doc);
  api.refresh();
  let roots = api.provider.getChildren();
  const node = roots[0].children[0];
  const item = api.provider.getTreeItem(node);
  assert.equal(item.label, '🇭🇰 Test');
  assert.equal(item.description, 'socks5');
  assert.equal(item.iconPath.id, 'symbol-module');
  await vscode.commands.executeCommand(item.command.command, ...item.command.arguments);
  assert.equal(vscode.window.activeTextEditor.selection.active.line, 1);
  assert.equal(vscode.window.activeTextEditor.selection.active.character, 4);
  const group = roots[1].children[0];
  assert.deepEqual(group.children.map(n => n.label), ['DIRECT', '🇭🇰 Test']);
  const member = api.provider.getTreeItem(group.children[1]);
  assert.equal(member.label, '🇭🇰 Test');
  assert.equal(member.iconPath.id, 'symbol-string');
  await vscode.commands.executeCommand(member.command.command, ...member.command.arguments);
  assert.equal(vscode.window.activeTextEditor.selection.active.line, 8);
  assert.equal(vscode.window.activeTextEditor.selection.active.character, 8);
  const editor = vscode.window.activeTextEditor;
  await editor.edit(builder => builder.insert(new vscode.Position(0, 0), '# inserted\n'));
  await new Promise(resolve => setTimeout(resolve, 350));
  roots = api.provider.getChildren();
  assert.equal(roots[0].children[0].line, 2);
  // An old tree command must not jump using stale offsets.
  const before = editor.selection.active;
  await vscode.commands.executeCommand(item.command.command, ...item.command.arguments);
  assert(editor.selection.active.isEqual(before));
  const setting = vscode.workspace.getConfiguration('mihomoNavigator');
  await setting.update('enableDocumentSymbols', true, vscode.ConfigurationTarget.Global);
  await new Promise(resolve => setTimeout(resolve, 150));
  const symbols = await vscode.commands.executeCommand('vscode.executeDocumentSymbolProvider', doc.uri);
  assert(symbols.some(s => s.name === 'proxies' && s.children?.[0].name === '🇭🇰 Test'));
  assert(symbols.some(s => s.name === 'proxy-groups' && s.children?.[0].children?.[1].name === '🇭🇰 Test'));
  assert.equal(symbols.find(s => s.name === 'proxies').kind, vscode.SymbolKind.Array);
  await setting.update('enableDocumentSymbols', false, vscode.ConfigurationTarget.Global);
  const nestedDoc = await vscode.workspace.openTextDocument({language: 'yaml', content: 'dns:\n  enable: true\n  nameserver:\n    - 1.1.1.1\n'});
  await vscode.window.showTextDocument(nestedDoc);
  api.refresh();
  const dns = api.provider.getChildren()[0];
  const enable = api.provider.getTreeItem(dns.children[0]);
  assert.equal(enable.description, ': true');
  assert.equal(enable.iconPath.id, 'symbol-boolean');
  assert.equal(api.provider.getTreeItem(dns.children[1]).iconPath.id, 'symbol-array');
  const server = api.provider.getTreeItem(dns.children[1].children[0]);
  await vscode.commands.executeCommand(server.command.command, ...server.command.arguments);
  assert.equal(vscode.window.activeTextEditor.selection.active.line, 3);
  const other = await vscode.workspace.openTextDocument({language: 'plaintext', content: 'Hello'});
  await vscode.window.showTextDocument(other);
  api.refresh();
  assert.equal(api.provider.getChildren().length, 0);
  console.log('Integration passed: activation, tree labels/type, jump, edits, stale commands, native symbols, editor switch.');
};
